language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nishab/docker-react -f Dockerfile.dev .

script:
  - docker run nishab/docker-react npm run test -- --coverage